name: trying to live up to the hype
favicon: null
layout_spectrum: 0.87748
typography_spectrum: 0.7832
title: live up to the hype
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e0ded2'
    - '#28889e'
    - '#b9bfbb'
    - '#59a9a8'
    - '#0f3d60'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.01043693907558918
  rhythmicContrast: 0.75
purpose: []
