name: trying to live up to the hype
favicon: null
layout_spectrum: 0.9081947039812803
typography_spectrum: 0.4489690433256328
title: live up to the hype
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08744546864181757
  lightness: 0.7858636898454279
  saturation: 0.01043693907558918
  rhythmicContrast: 0.6558106194715947
purpose: []
